//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Fbx {

public class FbxCollection : FbxObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal FbxCollection(global::System.IntPtr cPtr, bool cMemoryOwn) : base(fbx_wrapperPINVOKE.FbxCollection_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxCollection obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static SWIGTYPE_p_FbxClassId ClassId {
    set {
      fbx_wrapperPINVOKE.FbxCollection_ClassId_set(SWIGTYPE_p_FbxClassId.getCPtr(value));
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_FbxClassId ret = new SWIGTYPE_p_FbxClassId(fbx_wrapperPINVOKE.FbxCollection_ClassId_get(), true);
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public override SWIGTYPE_p_FbxClassId GetClassId() {
    SWIGTYPE_p_FbxClassId ret = new SWIGTYPE_p_FbxClassId(fbx_wrapperPINVOKE.FbxCollection_GetClassId(swigCPtr), true);
    return ret;
  }

  public new static FbxCollection Create(FbxManager pManager, string pName) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxCollection_Create__SWIG_0(FbxManager.getCPtr(pManager), pName);
    FbxCollection ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxCollection(cPtr, false);
    return ret;
  }

  public new static FbxCollection Create(FbxObject pContainer, string pName) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxCollection_Create__SWIG_1(FbxObject.getCPtr(pContainer), pName);
    FbxCollection ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxCollection(cPtr, false);
    return ret;
  }

  public virtual void Clear() {
    fbx_wrapperPINVOKE.FbxCollection_Clear(swigCPtr);
  }

  public virtual bool AddMember(FbxObject pMember) {
    bool ret = fbx_wrapperPINVOKE.FbxCollection_AddMember(swigCPtr, FbxObject.getCPtr(pMember));
    return ret;
  }

  public virtual bool RemoveMember(FbxObject pMember) {
    bool ret = fbx_wrapperPINVOKE.FbxCollection_RemoveMember(swigCPtr, FbxObject.getCPtr(pMember));
    return ret;
  }

  public int GetMemberCount() {
    int ret = fbx_wrapperPINVOKE.FbxCollection_GetMemberCount__SWIG_0(swigCPtr);
    return ret;
  }

  public FbxObject GetMember(int pIndex) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxCollection_GetMember__SWIG_0(swigCPtr, pIndex);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

  public FbxObject GetMember() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxCollection_GetMember__SWIG_1(swigCPtr);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

  public virtual bool IsMember(FbxObject pMember) {
    bool ret = fbx_wrapperPINVOKE.FbxCollection_IsMember(swigCPtr, FbxObject.getCPtr(pMember));
    return ret;
  }

  public int GetMemberCount(SWIGTYPE_p_FbxCriteria pCriteria) {
    int ret = fbx_wrapperPINVOKE.FbxCollection_GetMemberCount__SWIG_2(swigCPtr, SWIGTYPE_p_FbxCriteria.getCPtr(pCriteria));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxObject GetMember(SWIGTYPE_p_FbxCriteria pCriteria, int pIndex) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxCollection_GetMember__SWIG_4(swigCPtr, SWIGTYPE_p_FbxCriteria.getCPtr(pCriteria), pIndex);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxObject GetMember(SWIGTYPE_p_FbxCriteria pCriteria) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxCollection_GetMember__SWIG_5(swigCPtr, SWIGTYPE_p_FbxCriteria.getCPtr(pCriteria));
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxObject FindMember(SWIGTYPE_p_FbxCriteria pCriteria, string pName) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxCollection_FindMember(swigCPtr, SWIGTYPE_p_FbxCriteria.getCPtr(pCriteria), pName);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetSelectedAll(bool pSelection) {
    fbx_wrapperPINVOKE.FbxCollection_SetSelectedAll(swigCPtr, pSelection);
  }

}

}
