//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Fbx {

public class FbxDocument : FbxCollection {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal FbxDocument(global::System.IntPtr cPtr, bool cMemoryOwn) : base(fbx_wrapperPINVOKE.FbxDocument_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxDocument obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static SWIGTYPE_p_FbxClassId ClassId {
    set {
      fbx_wrapperPINVOKE.FbxDocument_ClassId_set(SWIGTYPE_p_FbxClassId.getCPtr(value));
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_FbxClassId ret = new SWIGTYPE_p_FbxClassId(fbx_wrapperPINVOKE.FbxDocument_ClassId_get(), true);
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public override SWIGTYPE_p_FbxClassId GetClassId() {
    SWIGTYPE_p_FbxClassId ret = new SWIGTYPE_p_FbxClassId(fbx_wrapperPINVOKE.FbxDocument_GetClassId(swigCPtr), true);
    return ret;
  }

  public new static FbxDocument Create(FbxManager pManager, string pName) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxDocument_Create__SWIG_0(FbxManager.getCPtr(pManager), pName);
    FbxDocument ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxDocument(cPtr, false);
    return ret;
  }

  public new static FbxDocument Create(FbxObject pContainer, string pName) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxDocument_Create__SWIG_1(FbxObject.getCPtr(pContainer), pName);
    FbxDocument ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxDocument(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_FbxPropertyTT_FbxObject_p_t Roots {
    set {
      fbx_wrapperPINVOKE.FbxDocument_Roots_set(swigCPtr, SWIGTYPE_p_FbxPropertyTT_FbxObject_p_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxDocument_Roots_get(swigCPtr);
      SWIGTYPE_p_FbxPropertyTT_FbxObject_p_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxPropertyTT_FbxObject_p_t(cPtr, false);
      return ret;
    } 
  }

  public override void Clear() {
    fbx_wrapperPINVOKE.FbxDocument_Clear(swigCPtr);
  }

  public void AddRootMember(FbxObject pMember) {
    fbx_wrapperPINVOKE.FbxDocument_AddRootMember(swigCPtr, FbxObject.getCPtr(pMember));
  }

  public void RootRootRemoveMember(FbxObject pMember) {
    fbx_wrapperPINVOKE.FbxDocument_RootRootRemoveMember(swigCPtr, FbxObject.getCPtr(pMember));
  }

  public int GetRootMemberCount() {
    int ret = fbx_wrapperPINVOKE.FbxDocument_GetRootMemberCount__SWIG_0(swigCPtr);
    return ret;
  }

  public int GetRootMemberCount(SWIGTYPE_p_FbxCriteria pCriteria) {
    int ret = fbx_wrapperPINVOKE.FbxDocument_GetRootMemberCount__SWIG_2(swigCPtr, SWIGTYPE_p_FbxCriteria.getCPtr(pCriteria));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxObject GetRootMember(int pIndex) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxDocument_GetRootMember__SWIG_0(swigCPtr, pIndex);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

  public FbxObject GetRootMember() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxDocument_GetRootMember__SWIG_1(swigCPtr);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

  public FbxObject GetRootMember(SWIGTYPE_p_FbxCriteria pCriteria, int pIndex) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxDocument_GetRootMember__SWIG_4(swigCPtr, SWIGTYPE_p_FbxCriteria.getCPtr(pCriteria), pIndex);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxObject GetRootMember(SWIGTYPE_p_FbxCriteria pCriteria) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxDocument_GetRootMember__SWIG_5(swigCPtr, SWIGTYPE_p_FbxCriteria.getCPtr(pCriteria));
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool IsRootMember(FbxObject pMember) {
    bool ret = fbx_wrapperPINVOKE.FbxDocument_IsRootMember(swigCPtr, FbxObject.getCPtr(pMember));
    return ret;
  }

  public FbxDocumentInfo GetDocumentInfo() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxDocument_GetDocumentInfo(swigCPtr);
    FbxDocumentInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxDocumentInfo(cPtr, false);
    return ret;
  }

  public void SetDocumentInfo(FbxDocumentInfo pSceneInfo) {
    fbx_wrapperPINVOKE.FbxDocument_SetDocumentInfo(swigCPtr, FbxDocumentInfo.getCPtr(pSceneInfo));
  }

  public void SetPeripheral(SWIGTYPE_p_FbxPeripheral pPeripheral) {
    fbx_wrapperPINVOKE.FbxDocument_SetPeripheral(swigCPtr, SWIGTYPE_p_FbxPeripheral.getCPtr(pPeripheral));
  }

  public virtual SWIGTYPE_p_FbxPeripheral GetPeripheral() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxDocument_GetPeripheral(swigCPtr);
    SWIGTYPE_p_FbxPeripheral ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxPeripheral(cPtr, false);
    return ret;
  }

  public int UnloadContent(SWIGTYPE_p_FbxStatus pStatus) {
    int ret = fbx_wrapperPINVOKE.FbxDocument_UnloadContent__SWIG_0(swigCPtr, SWIGTYPE_p_FbxStatus.getCPtr(pStatus));
    return ret;
  }

  public int UnloadContent() {
    int ret = fbx_wrapperPINVOKE.FbxDocument_UnloadContent__SWIG_1(swigCPtr);
    return ret;
  }

  public int LoadContent(SWIGTYPE_p_FbxStatus pStatus) {
    int ret = fbx_wrapperPINVOKE.FbxDocument_LoadContent__SWIG_0(swigCPtr, SWIGTYPE_p_FbxStatus.getCPtr(pStatus));
    return ret;
  }

  public int LoadContent() {
    int ret = fbx_wrapperPINVOKE.FbxDocument_LoadContent__SWIG_1(swigCPtr);
    return ret;
  }

  public int GetReferencingDocuments(SWIGTYPE_p_FbxArrayT_FbxDocument_p_t pReferencingDocuments) {
    int ret = fbx_wrapperPINVOKE.FbxDocument_GetReferencingDocuments(swigCPtr, SWIGTYPE_p_FbxArrayT_FbxDocument_p_t.getCPtr(pReferencingDocuments));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int GetReferencingObjects(FbxDocument pFromDoc, SWIGTYPE_p_FbxArrayT_FbxObject_p_t pReferencingObjects) {
    int ret = fbx_wrapperPINVOKE.FbxDocument_GetReferencingObjects(swigCPtr, FbxDocument.getCPtr(pFromDoc), SWIGTYPE_p_FbxArrayT_FbxObject_p_t.getCPtr(pReferencingObjects));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int GetReferencedDocuments(SWIGTYPE_p_FbxArrayT_FbxDocument_p_t pReferencedDocuments) {
    int ret = fbx_wrapperPINVOKE.FbxDocument_GetReferencedDocuments(swigCPtr, SWIGTYPE_p_FbxArrayT_FbxDocument_p_t.getCPtr(pReferencedDocuments));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int GetReferencedObjects(FbxDocument pToDoc, SWIGTYPE_p_FbxArrayT_FbxObject_p_t pReferencedObjects) {
    int ret = fbx_wrapperPINVOKE.FbxDocument_GetReferencedObjects(swigCPtr, FbxDocument.getCPtr(pToDoc), SWIGTYPE_p_FbxArrayT_FbxObject_p_t.getCPtr(pReferencedObjects));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_FbxString GetPathToRootDocument() {
    SWIGTYPE_p_FbxString ret = new SWIGTYPE_p_FbxString(fbx_wrapperPINVOKE.FbxDocument_GetPathToRootDocument(swigCPtr), true);
    return ret;
  }

  public void GetDocumentPathToRootDocument(SWIGTYPE_p_FbxArrayT_FbxDocument_p_t pDocumentPath, bool pFirstCall) {
    fbx_wrapperPINVOKE.FbxDocument_GetDocumentPathToRootDocument__SWIG_0(swigCPtr, SWIGTYPE_p_FbxArrayT_FbxDocument_p_t.getCPtr(pDocumentPath), pFirstCall);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetDocumentPathToRootDocument(SWIGTYPE_p_FbxArrayT_FbxDocument_p_t pDocumentPath) {
    fbx_wrapperPINVOKE.FbxDocument_GetDocumentPathToRootDocument__SWIG_1(swigCPtr, SWIGTYPE_p_FbxArrayT_FbxDocument_p_t.getCPtr(pDocumentPath));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool IsARootDocument() {
    bool ret = fbx_wrapperPINVOKE.FbxDocument_IsARootDocument(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_FbxPropertyTT_FbxString_t ActiveAnimStackName {
    set {
      fbx_wrapperPINVOKE.FbxDocument_ActiveAnimStackName_set(swigCPtr, SWIGTYPE_p_FbxPropertyTT_FbxString_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxDocument_ActiveAnimStackName_get(swigCPtr);
      SWIGTYPE_p_FbxPropertyTT_FbxString_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxPropertyTT_FbxString_t(cPtr, false);
      return ret;
    } 
  }

  public bool CreateAnimStack(string pName, SWIGTYPE_p_FbxStatus pStatus) {
    bool ret = fbx_wrapperPINVOKE.FbxDocument_CreateAnimStack__SWIG_0(swigCPtr, pName, SWIGTYPE_p_FbxStatus.getCPtr(pStatus));
    return ret;
  }

  public bool CreateAnimStack(string pName) {
    bool ret = fbx_wrapperPINVOKE.FbxDocument_CreateAnimStack__SWIG_1(swigCPtr, pName);
    return ret;
  }

  public bool RemoveAnimStack(string pName) {
    bool ret = fbx_wrapperPINVOKE.FbxDocument_RemoveAnimStack(swigCPtr, pName);
    return ret;
  }

  public void FillAnimStackNameArray(SWIGTYPE_p_FbxArrayT_FbxString_p_t pNameArray) {
    fbx_wrapperPINVOKE.FbxDocument_FillAnimStackNameArray(swigCPtr, SWIGTYPE_p_FbxArrayT_FbxString_p_t.getCPtr(pNameArray));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool SetTakeInfo(SWIGTYPE_p_FbxTakeInfo pTakeInfo) {
    bool ret = fbx_wrapperPINVOKE.FbxDocument_SetTakeInfo(swigCPtr, SWIGTYPE_p_FbxTakeInfo.getCPtr(pTakeInfo));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_FbxTakeInfo GetTakeInfo(SWIGTYPE_p_FbxString pTakeName) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxDocument_GetTakeInfo(swigCPtr, SWIGTYPE_p_FbxString.getCPtr(pTakeName));
    SWIGTYPE_p_FbxTakeInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxTakeInfo(cPtr, false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override FbxObject Copy(FbxObject pObject) {
    FbxObject ret = new FbxObject(fbx_wrapperPINVOKE.FbxDocument_Copy(swigCPtr, FbxObject.getCPtr(pObject)), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void Compact() {
    fbx_wrapperPINVOKE.FbxDocument_Compact(swigCPtr);
  }

  public void ConnectVideos() {
    fbx_wrapperPINVOKE.FbxDocument_ConnectVideos(swigCPtr);
  }

}

}
