//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Fbx {

public class FbxIOInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FbxIOInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxIOInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FbxIOInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          fbx_wrapperPINVOKE.delete_FbxIOInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public FbxIOInfo() : this(fbx_wrapperPINVOKE.new_FbxIOInfo(), true) {
  }

  public void Reset(FbxIOInfo.EImpExp pImpExp) {
    fbx_wrapperPINVOKE.FbxIOInfo_Reset(swigCPtr, (int)pImpExp);
  }

  public void SetTimeMode(SWIGTYPE_p_FbxTime__EMode pTimeMode, double pCustomFrameRate) {
    fbx_wrapperPINVOKE.FbxIOInfo_SetTimeMode__SWIG_0(swigCPtr, SWIGTYPE_p_FbxTime__EMode.getCPtr(pTimeMode), pCustomFrameRate);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetTimeMode(SWIGTYPE_p_FbxTime__EMode pTimeMode) {
    fbx_wrapperPINVOKE.FbxIOInfo_SetTimeMode__SWIG_1(swigCPtr, SWIGTYPE_p_FbxTime__EMode.getCPtr(pTimeMode));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_FbxTime__EMode GetTimeMode() {
    SWIGTYPE_p_FbxTime__EMode ret = new SWIGTYPE_p_FbxTime__EMode(fbx_wrapperPINVOKE.FbxIOInfo_GetTimeMode(swigCPtr), true);
    return ret;
  }

  public SWIGTYPE_p_FbxTime GetFramePeriod() {
    SWIGTYPE_p_FbxTime ret = new SWIGTYPE_p_FbxTime(fbx_wrapperPINVOKE.FbxIOInfo_GetFramePeriod(swigCPtr), true);
    return ret;
  }

  public void SetASFScene(FbxObject pASFScene, bool pASFSceneOwned) {
    fbx_wrapperPINVOKE.FbxIOInfo_SetASFScene__SWIG_0(swigCPtr, FbxObject.getCPtr(pASFScene), pASFSceneOwned);
  }

  public void SetASFScene(FbxObject pASFScene) {
    fbx_wrapperPINVOKE.FbxIOInfo_SetASFScene__SWIG_1(swigCPtr, FbxObject.getCPtr(pASFScene));
  }

  public FbxObject GetASFScene() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxIOInfo_GetASFScene(swigCPtr);
    FbxObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxObject(cPtr, false);
    return ret;
  }

  public void Set_IOS(FbxIOSettings pIOS) {
    fbx_wrapperPINVOKE.FbxIOInfo_Set_IOS(swigCPtr, FbxIOSettings.getCPtr(pIOS));
  }

  public void SetImportExportMode(FbxIOInfo.EImpExp pImpExp) {
    fbx_wrapperPINVOKE.FbxIOInfo_SetImportExportMode(swigCPtr, (int)pImpExp);
  }

  public enum EImpExp {
    eImport,
    eExport
  }

}

}
