//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Fbx {

public class FbxNode : FbxObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal FbxNode(global::System.IntPtr cPtr, bool cMemoryOwn) : base(fbx_wrapperPINVOKE.FbxNode_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxNode obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static SWIGTYPE_p_FbxClassId ClassId {
    set {
      fbx_wrapperPINVOKE.FbxNode_ClassId_set(SWIGTYPE_p_FbxClassId.getCPtr(value));
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_FbxClassId ret = new SWIGTYPE_p_FbxClassId(fbx_wrapperPINVOKE.FbxNode_ClassId_get(), true);
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public override SWIGTYPE_p_FbxClassId GetClassId() {
    SWIGTYPE_p_FbxClassId ret = new SWIGTYPE_p_FbxClassId(fbx_wrapperPINVOKE.FbxNode_GetClassId(swigCPtr), true);
    return ret;
  }

  public new static FbxNode Create(FbxManager pManager, string pName) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_Create__SWIG_0(FbxManager.getCPtr(pManager), pName);
    FbxNode ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxNode(cPtr, false);
    return ret;
  }

  public new static FbxNode Create(FbxObject pContainer, string pName) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_Create__SWIG_1(FbxObject.getCPtr(pContainer), pName);
    FbxNode ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxNode(cPtr, false);
    return ret;
  }

  public FbxNode GetParent() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GetParent__SWIG_0(swigCPtr);
    FbxNode ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxNode(cPtr, false);
    return ret;
  }

  public bool AddChild(FbxNode pNode) {
    bool ret = fbx_wrapperPINVOKE.FbxNode_AddChild(swigCPtr, FbxNode.getCPtr(pNode));
    return ret;
  }

  public FbxNode RemoveChild(FbxNode pNode) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_RemoveChild(swigCPtr, FbxNode.getCPtr(pNode));
    FbxNode ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxNode(cPtr, false);
    return ret;
  }

  public int GetChildCount(bool pRecursive) {
    int ret = fbx_wrapperPINVOKE.FbxNode_GetChildCount__SWIG_0(swigCPtr, pRecursive);
    return ret;
  }

  public int GetChildCount() {
    int ret = fbx_wrapperPINVOKE.FbxNode_GetChildCount__SWIG_1(swigCPtr);
    return ret;
  }

  public FbxNode GetChild(int pIndex) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GetChild__SWIG_0(swigCPtr, pIndex);
    FbxNode ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxNode(cPtr, false);
    return ret;
  }

  public FbxNode FindChild(string pName, bool pRecursive, bool pInitial) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_FindChild__SWIG_0(swigCPtr, pName, pRecursive, pInitial);
    FbxNode ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxNode(cPtr, false);
    return ret;
  }

  public FbxNode FindChild(string pName, bool pRecursive) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_FindChild__SWIG_1(swigCPtr, pName, pRecursive);
    FbxNode ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxNode(cPtr, false);
    return ret;
  }

  public FbxNode FindChild(string pName) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_FindChild__SWIG_2(swigCPtr, pName);
    FbxNode ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxNode(cPtr, false);
    return ret;
  }

  public void SetTarget(FbxNode pNode) {
    fbx_wrapperPINVOKE.FbxNode_SetTarget(swigCPtr, FbxNode.getCPtr(pNode));
  }

  public FbxNode GetTarget() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GetTarget(swigCPtr);
    FbxNode ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxNode(cPtr, false);
    return ret;
  }

  public void SetPostTargetRotation(FbxVector4 pVector) {
    fbx_wrapperPINVOKE.FbxNode_SetPostTargetRotation(swigCPtr, FbxVector4.getCPtr(pVector));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxVector4 GetPostTargetRotation() {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_GetPostTargetRotation(swigCPtr), true);
    return ret;
  }

  public void SetTargetUp(FbxNode pNode) {
    fbx_wrapperPINVOKE.FbxNode_SetTargetUp(swigCPtr, FbxNode.getCPtr(pNode));
  }

  public FbxNode GetTargetUp() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GetTargetUp(swigCPtr);
    FbxNode ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxNode(cPtr, false);
    return ret;
  }

  public void SetTargetUpVector(FbxVector4 pVector) {
    fbx_wrapperPINVOKE.FbxNode_SetTargetUpVector(swigCPtr, FbxVector4.getCPtr(pVector));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxVector4 GetTargetUpVector() {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_GetTargetUpVector(swigCPtr), true);
    return ret;
  }

  public void SetVisibility(bool pIsVisible) {
    fbx_wrapperPINVOKE.FbxNode_SetVisibility(swigCPtr, pIsVisible);
  }

  public bool GetVisibility() {
    bool ret = fbx_wrapperPINVOKE.FbxNode_GetVisibility(swigCPtr);
    return ret;
  }

  public void SetShadingMode(FbxNode.EShadingMode pShadingMode) {
    fbx_wrapperPINVOKE.FbxNode_SetShadingMode(swigCPtr, (int)pShadingMode);
  }

  public FbxNode.EShadingMode GetShadingMode() {
    FbxNode.EShadingMode ret = (FbxNode.EShadingMode)fbx_wrapperPINVOKE.FbxNode_GetShadingMode(swigCPtr);
    return ret;
  }

  public FbxNodeAttribute SetNodeAttribute(FbxNodeAttribute pNodeAttribute) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_SetNodeAttribute(swigCPtr, FbxNodeAttribute.getCPtr(pNodeAttribute));
    FbxNodeAttribute ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxNodeAttribute(cPtr, false);
    return ret;
  }

  public FbxNodeAttribute GetNodeAttribute() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GetNodeAttribute__SWIG_0(swigCPtr);
    FbxNodeAttribute ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxNodeAttribute(cPtr, false);
    return ret;
  }

  public int GetNodeAttributeCount() {
    int ret = fbx_wrapperPINVOKE.FbxNode_GetNodeAttributeCount(swigCPtr);
    return ret;
  }

  public int GetDefaultNodeAttributeIndex() {
    int ret = fbx_wrapperPINVOKE.FbxNode_GetDefaultNodeAttributeIndex(swigCPtr);
    return ret;
  }

  public bool SetDefaultNodeAttributeIndex(int pIndex, SWIGTYPE_p_FbxStatus pStatus) {
    bool ret = fbx_wrapperPINVOKE.FbxNode_SetDefaultNodeAttributeIndex__SWIG_0(swigCPtr, pIndex, SWIGTYPE_p_FbxStatus.getCPtr(pStatus));
    return ret;
  }

  public bool SetDefaultNodeAttributeIndex(int pIndex) {
    bool ret = fbx_wrapperPINVOKE.FbxNode_SetDefaultNodeAttributeIndex__SWIG_1(swigCPtr, pIndex);
    return ret;
  }

  public FbxNodeAttribute GetNodeAttributeByIndex(int pIndex) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GetNodeAttributeByIndex__SWIG_0(swigCPtr, pIndex);
    FbxNodeAttribute ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxNodeAttribute(cPtr, false);
    return ret;
  }

  public int GetNodeAttributeIndex(FbxNodeAttribute pNodeAttribute, SWIGTYPE_p_FbxStatus pStatus) {
    int ret = fbx_wrapperPINVOKE.FbxNode_GetNodeAttributeIndex__SWIG_0(swigCPtr, FbxNodeAttribute.getCPtr(pNodeAttribute), SWIGTYPE_p_FbxStatus.getCPtr(pStatus));
    return ret;
  }

  public int GetNodeAttributeIndex(FbxNodeAttribute pNodeAttribute) {
    int ret = fbx_wrapperPINVOKE.FbxNode_GetNodeAttributeIndex__SWIG_1(swigCPtr, FbxNodeAttribute.getCPtr(pNodeAttribute));
    return ret;
  }

  public bool AddNodeAttribute(FbxNodeAttribute pNodeAttribute, SWIGTYPE_p_FbxStatus pStatus) {
    bool ret = fbx_wrapperPINVOKE.FbxNode_AddNodeAttribute__SWIG_0(swigCPtr, FbxNodeAttribute.getCPtr(pNodeAttribute), SWIGTYPE_p_FbxStatus.getCPtr(pStatus));
    return ret;
  }

  public bool AddNodeAttribute(FbxNodeAttribute pNodeAttribute) {
    bool ret = fbx_wrapperPINVOKE.FbxNode_AddNodeAttribute__SWIG_1(swigCPtr, FbxNodeAttribute.getCPtr(pNodeAttribute));
    return ret;
  }

  public FbxNodeAttribute RemoveNodeAttribute(FbxNodeAttribute pNodeAttribute) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_RemoveNodeAttribute(swigCPtr, FbxNodeAttribute.getCPtr(pNodeAttribute));
    FbxNodeAttribute ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxNodeAttribute(cPtr, false);
    return ret;
  }

  public FbxNodeAttribute RemoveNodeAttributeByIndex(int pIndex) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_RemoveNodeAttributeByIndex(swigCPtr, pIndex);
    FbxNodeAttribute ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxNodeAttribute(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_FbxCachedEffect GetCachedEffect() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GetCachedEffect(swigCPtr);
    SWIGTYPE_p_FbxCachedEffect ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxCachedEffect(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_FbxLODGroup GetLodGroup() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GetLodGroup(swigCPtr);
    SWIGTYPE_p_FbxLODGroup ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxLODGroup(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_FbxNull GetNull() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GetNull(swigCPtr);
    SWIGTYPE_p_FbxNull ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxNull(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_FbxMarker GetMarker() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GetMarker(swigCPtr);
    SWIGTYPE_p_FbxMarker ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxMarker(cPtr, false);
    return ret;
  }

  public FbxSkeleton GetSkeleton() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GetSkeleton(swigCPtr);
    FbxSkeleton ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxSkeleton(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_FbxGeometry GetGeometry() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GetGeometry(swigCPtr);
    SWIGTYPE_p_FbxGeometry ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxGeometry(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_FbxMesh GetMesh() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GetMesh(swigCPtr);
    SWIGTYPE_p_FbxMesh ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxMesh(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_FbxNurbs GetNurbs() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GetNurbs(swigCPtr);
    SWIGTYPE_p_FbxNurbs ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxNurbs(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_FbxNurbsSurface GetNurbsSurface() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GetNurbsSurface(swigCPtr);
    SWIGTYPE_p_FbxNurbsSurface ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxNurbsSurface(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_FbxNurbsCurve GetNurbsCurve() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GetNurbsCurve(swigCPtr);
    SWIGTYPE_p_FbxNurbsCurve ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxNurbsCurve(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_FbxLine GetLine() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GetLine(swigCPtr);
    SWIGTYPE_p_FbxLine ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxLine(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_FbxTrimNurbsSurface GetTrimNurbsSurface() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GetTrimNurbsSurface(swigCPtr);
    SWIGTYPE_p_FbxTrimNurbsSurface ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxTrimNurbsSurface(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_FbxSubDiv GetSubdiv() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GetSubdiv(swigCPtr);
    SWIGTYPE_p_FbxSubDiv ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxSubDiv(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_FbxPatch GetPatch() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GetPatch(swigCPtr);
    SWIGTYPE_p_FbxPatch ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxPatch(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_FbxCamera GetCamera() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GetCamera__SWIG_0(swigCPtr);
    SWIGTYPE_p_FbxCamera ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxCamera(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_FbxCameraStereo GetCameraStereo() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GetCameraStereo(swigCPtr);
    SWIGTYPE_p_FbxCameraStereo ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxCameraStereo(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_FbxCameraSwitcher GetCameraSwitcher() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GetCameraSwitcher(swigCPtr);
    SWIGTYPE_p_FbxCameraSwitcher ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxCameraSwitcher(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_FbxLight GetLight() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GetLight__SWIG_0(swigCPtr);
    SWIGTYPE_p_FbxLight ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxLight(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_FbxOpticalReference GetOpticalReference() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GetOpticalReference(swigCPtr);
    SWIGTYPE_p_FbxOpticalReference ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxOpticalReference(cPtr, false);
    return ret;
  }

  public void SetTransformationInheritType(SWIGTYPE_p_FbxTransform__EInheritType pInheritType) {
    fbx_wrapperPINVOKE.FbxNode_SetTransformationInheritType(swigCPtr, SWIGTYPE_p_FbxTransform__EInheritType.getCPtr(pInheritType));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetTransformationInheritType(SWIGTYPE_p_FbxTransform__EInheritType pInheritType) {
    fbx_wrapperPINVOKE.FbxNode_GetTransformationInheritType(swigCPtr, SWIGTYPE_p_FbxTransform__EInheritType.getCPtr(pInheritType));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetPivotState(FbxNode.EPivotSet pPivotSet, FbxNode.EPivotState pPivotState) {
    fbx_wrapperPINVOKE.FbxNode_SetPivotState(swigCPtr, (int)pPivotSet, (int)pPivotState);
  }

  public void GetPivotState(FbxNode.EPivotSet pPivotSet, SWIGTYPE_p_FbxNode__EPivotState pPivotState) {
    fbx_wrapperPINVOKE.FbxNode_GetPivotState(swigCPtr, (int)pPivotSet, SWIGTYPE_p_FbxNode__EPivotState.getCPtr(pPivotState));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRotationOrder(FbxNode.EPivotSet pPivotSet, SWIGTYPE_p_EFbxRotationOrder pRotationOrder) {
    fbx_wrapperPINVOKE.FbxNode_SetRotationOrder(swigCPtr, (int)pPivotSet, SWIGTYPE_p_EFbxRotationOrder.getCPtr(pRotationOrder));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void GetRotationOrder(FbxNode.EPivotSet pPivotSet, SWIGTYPE_p_EFbxRotationOrder pRotationOrder) {
    fbx_wrapperPINVOKE.FbxNode_GetRotationOrder(swigCPtr, (int)pPivotSet, SWIGTYPE_p_EFbxRotationOrder.getCPtr(pRotationOrder));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetUseRotationSpaceForLimitOnly(FbxNode.EPivotSet pPivotSet, bool pUseForLimitOnly) {
    fbx_wrapperPINVOKE.FbxNode_SetUseRotationSpaceForLimitOnly(swigCPtr, (int)pPivotSet, pUseForLimitOnly);
  }

  public bool GetUseRotationSpaceForLimitOnly(FbxNode.EPivotSet pPivotSet) {
    bool ret = fbx_wrapperPINVOKE.FbxNode_GetUseRotationSpaceForLimitOnly(swigCPtr, (int)pPivotSet);
    return ret;
  }

  public void SetRotationActive(bool pVal) {
    fbx_wrapperPINVOKE.FbxNode_SetRotationActive(swigCPtr, pVal);
  }

  public bool GetRotationActive() {
    bool ret = fbx_wrapperPINVOKE.FbxNode_GetRotationActive(swigCPtr);
    return ret;
  }

  public void SetQuaternionInterpolation(FbxNode.EPivotSet pPivotSet, SWIGTYPE_p_EFbxQuatInterpMode pQuatIterp) {
    fbx_wrapperPINVOKE.FbxNode_SetQuaternionInterpolation(swigCPtr, (int)pPivotSet, SWIGTYPE_p_EFbxQuatInterpMode.getCPtr(pQuatIterp));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_EFbxQuatInterpMode GetQuaternionInterpolation(FbxNode.EPivotSet pPivotSet) {
    SWIGTYPE_p_EFbxQuatInterpMode ret = new SWIGTYPE_p_EFbxQuatInterpMode(fbx_wrapperPINVOKE.FbxNode_GetQuaternionInterpolation(swigCPtr, (int)pPivotSet), true);
    return ret;
  }

  public void SetRotationStiffness(FbxVector4 pRotationStiffness) {
    fbx_wrapperPINVOKE.FbxNode_SetRotationStiffness(swigCPtr, FbxVector4.getCPtr(pRotationStiffness));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxVector4 GetRotationStiffness() {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_GetRotationStiffness(swigCPtr), true);
    return ret;
  }

  public void SetMinDampRange(FbxVector4 pMinDampRange) {
    fbx_wrapperPINVOKE.FbxNode_SetMinDampRange(swigCPtr, FbxVector4.getCPtr(pMinDampRange));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxVector4 GetMinDampRange() {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_GetMinDampRange(swigCPtr), true);
    return ret;
  }

  public void SetMaxDampRange(FbxVector4 pMaxDampRange) {
    fbx_wrapperPINVOKE.FbxNode_SetMaxDampRange(swigCPtr, FbxVector4.getCPtr(pMaxDampRange));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxVector4 GetMaxDampRange() {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_GetMaxDampRange(swigCPtr), true);
    return ret;
  }

  public void SetMinDampStrength(FbxVector4 pMinDampStrength) {
    fbx_wrapperPINVOKE.FbxNode_SetMinDampStrength(swigCPtr, FbxVector4.getCPtr(pMinDampStrength));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxVector4 GetMinDampStrength() {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_GetMinDampStrength(swigCPtr), true);
    return ret;
  }

  public void SetMaxDampStrength(FbxVector4 pMaxDampStrength) {
    fbx_wrapperPINVOKE.FbxNode_SetMaxDampStrength(swigCPtr, FbxVector4.getCPtr(pMaxDampStrength));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxVector4 GetMaxDampStrength() {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_GetMaxDampStrength(swigCPtr), true);
    return ret;
  }

  public void SetPreferedAngle(FbxVector4 pPreferedAngle) {
    fbx_wrapperPINVOKE.FbxNode_SetPreferedAngle(swigCPtr, FbxVector4.getCPtr(pPreferedAngle));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxVector4 GetPreferedAngle() {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_GetPreferedAngle(swigCPtr), true);
    return ret;
  }

  public void SetRotationOffset(FbxNode.EPivotSet pPivotSet, FbxVector4 pVector) {
    fbx_wrapperPINVOKE.FbxNode_SetRotationOffset(swigCPtr, (int)pPivotSet, FbxVector4.getCPtr(pVector));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxVector4 GetRotationOffset(FbxNode.EPivotSet pPivotSet) {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_GetRotationOffset(swigCPtr, (int)pPivotSet), false);
    return ret;
  }

  public void SetRotationPivot(FbxNode.EPivotSet pPivotSet, FbxVector4 pVector) {
    fbx_wrapperPINVOKE.FbxNode_SetRotationPivot(swigCPtr, (int)pPivotSet, FbxVector4.getCPtr(pVector));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxVector4 GetRotationPivot(FbxNode.EPivotSet pPivotSet) {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_GetRotationPivot(swigCPtr, (int)pPivotSet), false);
    return ret;
  }

  public void SetPreRotation(FbxNode.EPivotSet pPivotSet, FbxVector4 pVector) {
    fbx_wrapperPINVOKE.FbxNode_SetPreRotation(swigCPtr, (int)pPivotSet, FbxVector4.getCPtr(pVector));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxVector4 GetPreRotation(FbxNode.EPivotSet pPivotSet) {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_GetPreRotation(swigCPtr, (int)pPivotSet), false);
    return ret;
  }

  public void SetPostRotation(FbxNode.EPivotSet pPivotSet, FbxVector4 pVector) {
    fbx_wrapperPINVOKE.FbxNode_SetPostRotation(swigCPtr, (int)pPivotSet, FbxVector4.getCPtr(pVector));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxVector4 GetPostRotation(FbxNode.EPivotSet pPivotSet) {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_GetPostRotation(swigCPtr, (int)pPivotSet), false);
    return ret;
  }

  public void SetScalingOffset(FbxNode.EPivotSet pPivotSet, FbxVector4 pVector) {
    fbx_wrapperPINVOKE.FbxNode_SetScalingOffset(swigCPtr, (int)pPivotSet, FbxVector4.getCPtr(pVector));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxVector4 GetScalingOffset(FbxNode.EPivotSet pPivotSet) {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_GetScalingOffset(swigCPtr, (int)pPivotSet), false);
    return ret;
  }

  public void SetScalingPivot(FbxNode.EPivotSet pPivotSet, FbxVector4 pVector) {
    fbx_wrapperPINVOKE.FbxNode_SetScalingPivot(swigCPtr, (int)pPivotSet, FbxVector4.getCPtr(pVector));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxVector4 GetScalingPivot(FbxNode.EPivotSet pPivotSet) {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_GetScalingPivot(swigCPtr, (int)pPivotSet), false);
    return ret;
  }

  public void SetGeometricTranslation(FbxNode.EPivotSet pPivotSet, FbxVector4 pVector) {
    fbx_wrapperPINVOKE.FbxNode_SetGeometricTranslation(swigCPtr, (int)pPivotSet, FbxVector4.getCPtr(pVector));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxVector4 GetGeometricTranslation(FbxNode.EPivotSet pPivotSet) {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_GetGeometricTranslation(swigCPtr, (int)pPivotSet), true);
    return ret;
  }

  public void SetGeometricRotation(FbxNode.EPivotSet pPivotSet, FbxVector4 pVector) {
    fbx_wrapperPINVOKE.FbxNode_SetGeometricRotation(swigCPtr, (int)pPivotSet, FbxVector4.getCPtr(pVector));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxVector4 GetGeometricRotation(FbxNode.EPivotSet pPivotSet) {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_GetGeometricRotation(swigCPtr, (int)pPivotSet), true);
    return ret;
  }

  public void SetGeometricScaling(FbxNode.EPivotSet pPivotSet, FbxVector4 pVector) {
    fbx_wrapperPINVOKE.FbxNode_SetGeometricScaling(swigCPtr, (int)pPivotSet, FbxVector4.getCPtr(pVector));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public FbxVector4 GetGeometricScaling(FbxNode.EPivotSet pPivotSet) {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_GetGeometricScaling(swigCPtr, (int)pPivotSet), true);
    return ret;
  }

  public void ResetPivotSet(FbxNode.EPivotSet pPivotSet) {
    fbx_wrapperPINVOKE.FbxNode_ResetPivotSet(swigCPtr, (int)pPivotSet);
  }

  public void ConvertPivotAnimationRecursive(FbxAnimStack pAnimStack, FbxNode.EPivotSet pConversionTarget, double pFrameRate, bool pKeyReduce) {
    fbx_wrapperPINVOKE.FbxNode_ConvertPivotAnimationRecursive__SWIG_0(swigCPtr, FbxAnimStack.getCPtr(pAnimStack), (int)pConversionTarget, pFrameRate, pKeyReduce);
  }

  public void ConvertPivotAnimationRecursive(FbxAnimStack pAnimStack, FbxNode.EPivotSet pConversionTarget, double pFrameRate) {
    fbx_wrapperPINVOKE.FbxNode_ConvertPivotAnimationRecursive__SWIG_1(swigCPtr, FbxAnimStack.getCPtr(pAnimStack), (int)pConversionTarget, pFrameRate);
  }

  public void ResetPivotSetAndConvertAnimation(double pFrameRate, bool pKeyReduce, bool pToNodeCenter, bool pForceResetLimits) {
    fbx_wrapperPINVOKE.FbxNode_ResetPivotSetAndConvertAnimation__SWIG_0(swigCPtr, pFrameRate, pKeyReduce, pToNodeCenter, pForceResetLimits);
  }

  public void ResetPivotSetAndConvertAnimation(double pFrameRate, bool pKeyReduce, bool pToNodeCenter) {
    fbx_wrapperPINVOKE.FbxNode_ResetPivotSetAndConvertAnimation__SWIG_1(swigCPtr, pFrameRate, pKeyReduce, pToNodeCenter);
  }

  public void ResetPivotSetAndConvertAnimation(double pFrameRate, bool pKeyReduce) {
    fbx_wrapperPINVOKE.FbxNode_ResetPivotSetAndConvertAnimation__SWIG_2(swigCPtr, pFrameRate, pKeyReduce);
  }

  public void ResetPivotSetAndConvertAnimation(double pFrameRate) {
    fbx_wrapperPINVOKE.FbxNode_ResetPivotSetAndConvertAnimation__SWIG_3(swigCPtr, pFrameRate);
  }

  public void ResetPivotSetAndConvertAnimation() {
    fbx_wrapperPINVOKE.FbxNode_ResetPivotSetAndConvertAnimation__SWIG_4(swigCPtr);
  }

  public void SetRotationPivotAsCenterRecursive(FbxVector4 pParentGeometricOffset) {
    fbx_wrapperPINVOKE.FbxNode_SetRotationPivotAsCenterRecursive__SWIG_0(swigCPtr, FbxVector4.getCPtr(pParentGeometricOffset));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRotationPivotAsCenterRecursive() {
    fbx_wrapperPINVOKE.FbxNode_SetRotationPivotAsCenterRecursive__SWIG_1(swigCPtr);
  }

  public FbxAnimEvaluator GetAnimationEvaluator() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GetAnimationEvaluator(swigCPtr);
    FbxAnimEvaluator ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxAnimEvaluator(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_FbxAMatrix EvaluateGlobalTransform(FbxTime pTime, FbxNode.EPivotSet pPivotSet, bool pApplyTarget, bool pForceEval) {
    SWIGTYPE_p_FbxAMatrix ret = new SWIGTYPE_p_FbxAMatrix(fbx_wrapperPINVOKE.FbxNode_EvaluateGlobalTransform__SWIG_0(swigCPtr, FbxTime.getCPtr(pTime), (int)pPivotSet, pApplyTarget, pForceEval), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_FbxAMatrix EvaluateGlobalTransform(FbxTime pTime, FbxNode.EPivotSet pPivotSet, bool pApplyTarget) {
    SWIGTYPE_p_FbxAMatrix ret = new SWIGTYPE_p_FbxAMatrix(fbx_wrapperPINVOKE.FbxNode_EvaluateGlobalTransform__SWIG_1(swigCPtr, FbxTime.getCPtr(pTime), (int)pPivotSet, pApplyTarget), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_FbxAMatrix EvaluateGlobalTransform(FbxTime pTime, FbxNode.EPivotSet pPivotSet) {
    SWIGTYPE_p_FbxAMatrix ret = new SWIGTYPE_p_FbxAMatrix(fbx_wrapperPINVOKE.FbxNode_EvaluateGlobalTransform__SWIG_2(swigCPtr, FbxTime.getCPtr(pTime), (int)pPivotSet), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_FbxAMatrix EvaluateGlobalTransform(FbxTime pTime) {
    SWIGTYPE_p_FbxAMatrix ret = new SWIGTYPE_p_FbxAMatrix(fbx_wrapperPINVOKE.FbxNode_EvaluateGlobalTransform__SWIG_3(swigCPtr, FbxTime.getCPtr(pTime)), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_FbxAMatrix EvaluateGlobalTransform() {
    SWIGTYPE_p_FbxAMatrix ret = new SWIGTYPE_p_FbxAMatrix(fbx_wrapperPINVOKE.FbxNode_EvaluateGlobalTransform__SWIG_4(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_FbxAMatrix EvaluateLocalTransform(FbxTime pTime, FbxNode.EPivotSet pPivotSet, bool pApplyTarget, bool pForceEval) {
    SWIGTYPE_p_FbxAMatrix ret = new SWIGTYPE_p_FbxAMatrix(fbx_wrapperPINVOKE.FbxNode_EvaluateLocalTransform__SWIG_0(swigCPtr, FbxTime.getCPtr(pTime), (int)pPivotSet, pApplyTarget, pForceEval), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_FbxAMatrix EvaluateLocalTransform(FbxTime pTime, FbxNode.EPivotSet pPivotSet, bool pApplyTarget) {
    SWIGTYPE_p_FbxAMatrix ret = new SWIGTYPE_p_FbxAMatrix(fbx_wrapperPINVOKE.FbxNode_EvaluateLocalTransform__SWIG_1(swigCPtr, FbxTime.getCPtr(pTime), (int)pPivotSet, pApplyTarget), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_FbxAMatrix EvaluateLocalTransform(FbxTime pTime, FbxNode.EPivotSet pPivotSet) {
    SWIGTYPE_p_FbxAMatrix ret = new SWIGTYPE_p_FbxAMatrix(fbx_wrapperPINVOKE.FbxNode_EvaluateLocalTransform__SWIG_2(swigCPtr, FbxTime.getCPtr(pTime), (int)pPivotSet), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_FbxAMatrix EvaluateLocalTransform(FbxTime pTime) {
    SWIGTYPE_p_FbxAMatrix ret = new SWIGTYPE_p_FbxAMatrix(fbx_wrapperPINVOKE.FbxNode_EvaluateLocalTransform__SWIG_3(swigCPtr, FbxTime.getCPtr(pTime)), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_FbxAMatrix EvaluateLocalTransform() {
    SWIGTYPE_p_FbxAMatrix ret = new SWIGTYPE_p_FbxAMatrix(fbx_wrapperPINVOKE.FbxNode_EvaluateLocalTransform__SWIG_4(swigCPtr), false);
    return ret;
  }

  public FbxVector4 EvaluateLocalTranslation(FbxTime pTime, FbxNode.EPivotSet pPivotSet, bool pApplyTarget, bool pForceEval) {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_EvaluateLocalTranslation__SWIG_0(swigCPtr, FbxTime.getCPtr(pTime), (int)pPivotSet, pApplyTarget, pForceEval), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxVector4 EvaluateLocalTranslation(FbxTime pTime, FbxNode.EPivotSet pPivotSet, bool pApplyTarget) {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_EvaluateLocalTranslation__SWIG_1(swigCPtr, FbxTime.getCPtr(pTime), (int)pPivotSet, pApplyTarget), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxVector4 EvaluateLocalTranslation(FbxTime pTime, FbxNode.EPivotSet pPivotSet) {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_EvaluateLocalTranslation__SWIG_2(swigCPtr, FbxTime.getCPtr(pTime), (int)pPivotSet), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxVector4 EvaluateLocalTranslation(FbxTime pTime) {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_EvaluateLocalTranslation__SWIG_3(swigCPtr, FbxTime.getCPtr(pTime)), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxVector4 EvaluateLocalTranslation() {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_EvaluateLocalTranslation__SWIG_4(swigCPtr), false);
    return ret;
  }

  public FbxVector4 EvaluateLocalRotation(FbxTime pTime, FbxNode.EPivotSet pPivotSet, bool pApplyTarget, bool pForceEval) {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_EvaluateLocalRotation__SWIG_0(swigCPtr, FbxTime.getCPtr(pTime), (int)pPivotSet, pApplyTarget, pForceEval), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxVector4 EvaluateLocalRotation(FbxTime pTime, FbxNode.EPivotSet pPivotSet, bool pApplyTarget) {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_EvaluateLocalRotation__SWIG_1(swigCPtr, FbxTime.getCPtr(pTime), (int)pPivotSet, pApplyTarget), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxVector4 EvaluateLocalRotation(FbxTime pTime, FbxNode.EPivotSet pPivotSet) {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_EvaluateLocalRotation__SWIG_2(swigCPtr, FbxTime.getCPtr(pTime), (int)pPivotSet), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxVector4 EvaluateLocalRotation(FbxTime pTime) {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_EvaluateLocalRotation__SWIG_3(swigCPtr, FbxTime.getCPtr(pTime)), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxVector4 EvaluateLocalRotation() {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_EvaluateLocalRotation__SWIG_4(swigCPtr), false);
    return ret;
  }

  public FbxVector4 EvaluateLocalScaling(FbxTime pTime, FbxNode.EPivotSet pPivotSet, bool pApplyTarget, bool pForceEval) {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_EvaluateLocalScaling__SWIG_0(swigCPtr, FbxTime.getCPtr(pTime), (int)pPivotSet, pApplyTarget, pForceEval), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxVector4 EvaluateLocalScaling(FbxTime pTime, FbxNode.EPivotSet pPivotSet, bool pApplyTarget) {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_EvaluateLocalScaling__SWIG_1(swigCPtr, FbxTime.getCPtr(pTime), (int)pPivotSet, pApplyTarget), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxVector4 EvaluateLocalScaling(FbxTime pTime, FbxNode.EPivotSet pPivotSet) {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_EvaluateLocalScaling__SWIG_2(swigCPtr, FbxTime.getCPtr(pTime), (int)pPivotSet), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxVector4 EvaluateLocalScaling(FbxTime pTime) {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_EvaluateLocalScaling__SWIG_3(swigCPtr, FbxTime.getCPtr(pTime)), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public FbxVector4 EvaluateLocalScaling() {
    FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_EvaluateLocalScaling__SWIG_4(swigCPtr), false);
    return ret;
  }

  public bool EvaluateGlobalBoundingBoxMinMaxCenter(FbxVector4 pBBoxMin, FbxVector4 pBBoxMax, FbxVector4 pBBoxCenter, FbxTime pTime) {
    bool ret = fbx_wrapperPINVOKE.FbxNode_EvaluateGlobalBoundingBoxMinMaxCenter__SWIG_0(swigCPtr, FbxVector4.getCPtr(pBBoxMin), FbxVector4.getCPtr(pBBoxMax), FbxVector4.getCPtr(pBBoxCenter), FbxTime.getCPtr(pTime));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool EvaluateGlobalBoundingBoxMinMaxCenter(FbxVector4 pBBoxMin, FbxVector4 pBBoxMax, FbxVector4 pBBoxCenter) {
    bool ret = fbx_wrapperPINVOKE.FbxNode_EvaluateGlobalBoundingBoxMinMaxCenter__SWIG_1(swigCPtr, FbxVector4.getCPtr(pBBoxMin), FbxVector4.getCPtr(pBBoxMax), FbxVector4.getCPtr(pBBoxCenter));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool EvaluateRayIntersectionPoint(FbxVector4 pOut, FbxVector4 pRayOrigin, FbxVector4 pRayDir, bool pCulling, FbxTime pTime) {
    bool ret = fbx_wrapperPINVOKE.FbxNode_EvaluateRayIntersectionPoint__SWIG_0(swigCPtr, FbxVector4.getCPtr(pOut), FbxVector4.getCPtr(pRayOrigin), FbxVector4.getCPtr(pRayDir), pCulling, FbxTime.getCPtr(pTime));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool EvaluateRayIntersectionPoint(FbxVector4 pOut, FbxVector4 pRayOrigin, FbxVector4 pRayDir, bool pCulling) {
    bool ret = fbx_wrapperPINVOKE.FbxNode_EvaluateRayIntersectionPoint__SWIG_1(swigCPtr, FbxVector4.getCPtr(pOut), FbxVector4.getCPtr(pRayOrigin), FbxVector4.getCPtr(pRayDir), pCulling);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool EvaluateRayIntersectionPoint(FbxVector4 pOut, FbxVector4 pRayOrigin, FbxVector4 pRayDir) {
    bool ret = fbx_wrapperPINVOKE.FbxNode_EvaluateRayIntersectionPoint__SWIG_2(swigCPtr, FbxVector4.getCPtr(pOut), FbxVector4.getCPtr(pRayOrigin), FbxVector4.getCPtr(pRayDir));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int GetCharacterLinkCount() {
    int ret = fbx_wrapperPINVOKE.FbxNode_GetCharacterLinkCount(swigCPtr);
    return ret;
  }

  public bool GetCharacterLink(int pIndex, SWIGTYPE_p_p_FbxCharacter pCharacter, SWIGTYPE_p_int pCharacterLinkType, SWIGTYPE_p_int pNodeId, SWIGTYPE_p_int pNodeSubId) {
    bool ret = fbx_wrapperPINVOKE.FbxNode_GetCharacterLink(swigCPtr, pIndex, SWIGTYPE_p_p_FbxCharacter.getCPtr(pCharacter), SWIGTYPE_p_int.getCPtr(pCharacterLinkType), SWIGTYPE_p_int.getCPtr(pNodeId), SWIGTYPE_p_int.getCPtr(pNodeSubId));
    return ret;
  }

  public int FindCharacterLink(SWIGTYPE_p_FbxCharacter pCharacter, int pCharacterLinkType, int pNodeId, int pNodeSubId) {
    int ret = fbx_wrapperPINVOKE.FbxNode_FindCharacterLink(swigCPtr, SWIGTYPE_p_FbxCharacter.getCPtr(pCharacter), pCharacterLinkType, pNodeId, pNodeSubId);
    return ret;
  }

  public bool GetAnimationInterval(FbxTimeSpan pInterval, FbxAnimStack pAnimStack, int pAnimLayerId) {
    bool ret = fbx_wrapperPINVOKE.FbxNode_GetAnimationInterval__SWIG_0(swigCPtr, FbxTimeSpan.getCPtr(pInterval), FbxAnimStack.getCPtr(pAnimStack), pAnimLayerId);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetAnimationInterval(FbxTimeSpan pInterval, FbxAnimStack pAnimStack) {
    bool ret = fbx_wrapperPINVOKE.FbxNode_GetAnimationInterval__SWIG_1(swigCPtr, FbxTimeSpan.getCPtr(pInterval), FbxAnimStack.getCPtr(pAnimStack));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GetAnimationInterval(FbxTimeSpan pInterval) {
    bool ret = fbx_wrapperPINVOKE.FbxNode_GetAnimationInterval__SWIG_2(swigCPtr, FbxTimeSpan.getCPtr(pInterval));
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int AddMaterial(SWIGTYPE_p_FbxSurfaceMaterial pMaterial) {
    int ret = fbx_wrapperPINVOKE.FbxNode_AddMaterial(swigCPtr, SWIGTYPE_p_FbxSurfaceMaterial.getCPtr(pMaterial));
    return ret;
  }

  public bool RemoveMaterial(SWIGTYPE_p_FbxSurfaceMaterial pMaterial) {
    bool ret = fbx_wrapperPINVOKE.FbxNode_RemoveMaterial(swigCPtr, SWIGTYPE_p_FbxSurfaceMaterial.getCPtr(pMaterial));
    return ret;
  }

  public int GetMaterialCount() {
    int ret = fbx_wrapperPINVOKE.FbxNode_GetMaterialCount(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_FbxSurfaceMaterial GetMaterial(int pIndex) {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GetMaterial(swigCPtr, pIndex);
    SWIGTYPE_p_FbxSurfaceMaterial ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxSurfaceMaterial(cPtr, false);
    return ret;
  }

  public void RemoveAllMaterials() {
    fbx_wrapperPINVOKE.FbxNode_RemoveAllMaterials(swigCPtr);
  }

  public int GetMaterialIndex(string pName) {
    int ret = fbx_wrapperPINVOKE.FbxNode_GetMaterialIndex(swigCPtr, pName);
    return ret;
  }

  public FbxPropertyDouble3 LclTranslation {
    set {
      fbx_wrapperPINVOKE.FbxNode_LclTranslation_set(swigCPtr, FbxPropertyDouble3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_LclTranslation_get(swigCPtr);
      FbxPropertyDouble3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble3(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble3 LclRotation {
    set {
      fbx_wrapperPINVOKE.FbxNode_LclRotation_set(swigCPtr, FbxPropertyDouble3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_LclRotation_get(swigCPtr);
      FbxPropertyDouble3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble3(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble3 LclScaling {
    set {
      fbx_wrapperPINVOKE.FbxNode_LclScaling_set(swigCPtr, FbxPropertyDouble3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_LclScaling_get(swigCPtr);
      FbxPropertyDouble3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble3(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble Visibility {
    set {
      fbx_wrapperPINVOKE.FbxNode_Visibility_set(swigCPtr, FbxPropertyDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_Visibility_get(swigCPtr);
      FbxPropertyDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyBool VisibilityInheritance {
    set {
      fbx_wrapperPINVOKE.FbxNode_VisibilityInheritance_set(swigCPtr, FbxPropertyBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_VisibilityInheritance_get(swigCPtr);
      FbxPropertyBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyBool(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_FbxPropertyTT_EFbxQuatInterpMode_t QuaternionInterpolate {
    set {
      fbx_wrapperPINVOKE.FbxNode_QuaternionInterpolate_set(swigCPtr, SWIGTYPE_p_FbxPropertyTT_EFbxQuatInterpMode_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_QuaternionInterpolate_get(swigCPtr);
      SWIGTYPE_p_FbxPropertyTT_EFbxQuatInterpMode_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxPropertyTT_EFbxQuatInterpMode_t(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble3 RotationOffset {
    set {
      fbx_wrapperPINVOKE.FbxNode_RotationOffset_set(swigCPtr, FbxPropertyDouble3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_RotationOffset_get(swigCPtr);
      FbxPropertyDouble3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble3(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble3 RotationPivot {
    set {
      fbx_wrapperPINVOKE.FbxNode_RotationPivot_set(swigCPtr, FbxPropertyDouble3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_RotationPivot_get(swigCPtr);
      FbxPropertyDouble3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble3(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble3 ScalingOffset {
    set {
      fbx_wrapperPINVOKE.FbxNode_ScalingOffset_set(swigCPtr, FbxPropertyDouble3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_ScalingOffset_get(swigCPtr);
      FbxPropertyDouble3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble3(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble3 ScalingPivot {
    set {
      fbx_wrapperPINVOKE.FbxNode_ScalingPivot_set(swigCPtr, FbxPropertyDouble3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_ScalingPivot_get(swigCPtr);
      FbxPropertyDouble3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble3(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyBool TranslationActive {
    set {
      fbx_wrapperPINVOKE.FbxNode_TranslationActive_set(swigCPtr, FbxPropertyBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_TranslationActive_get(swigCPtr);
      FbxPropertyBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble3 TranslationMin {
    set {
      fbx_wrapperPINVOKE.FbxNode_TranslationMin_set(swigCPtr, FbxPropertyDouble3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_TranslationMin_get(swigCPtr);
      FbxPropertyDouble3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble3(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble3 TranslationMax {
    set {
      fbx_wrapperPINVOKE.FbxNode_TranslationMax_set(swigCPtr, FbxPropertyDouble3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_TranslationMax_get(swigCPtr);
      FbxPropertyDouble3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble3(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyBool TranslationMinX {
    set {
      fbx_wrapperPINVOKE.FbxNode_TranslationMinX_set(swigCPtr, FbxPropertyBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_TranslationMinX_get(swigCPtr);
      FbxPropertyBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyBool TranslationMinY {
    set {
      fbx_wrapperPINVOKE.FbxNode_TranslationMinY_set(swigCPtr, FbxPropertyBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_TranslationMinY_get(swigCPtr);
      FbxPropertyBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyBool TranslationMinZ {
    set {
      fbx_wrapperPINVOKE.FbxNode_TranslationMinZ_set(swigCPtr, FbxPropertyBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_TranslationMinZ_get(swigCPtr);
      FbxPropertyBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyBool TranslationMaxX {
    set {
      fbx_wrapperPINVOKE.FbxNode_TranslationMaxX_set(swigCPtr, FbxPropertyBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_TranslationMaxX_get(swigCPtr);
      FbxPropertyBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyBool TranslationMaxY {
    set {
      fbx_wrapperPINVOKE.FbxNode_TranslationMaxY_set(swigCPtr, FbxPropertyBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_TranslationMaxY_get(swigCPtr);
      FbxPropertyBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyBool TranslationMaxZ {
    set {
      fbx_wrapperPINVOKE.FbxNode_TranslationMaxZ_set(swigCPtr, FbxPropertyBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_TranslationMaxZ_get(swigCPtr);
      FbxPropertyBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyBool(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_FbxPropertyTT_EFbxRotationOrder_t RotationOrder {
    set {
      fbx_wrapperPINVOKE.FbxNode_RotationOrder_set(swigCPtr, SWIGTYPE_p_FbxPropertyTT_EFbxRotationOrder_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_RotationOrder_get(swigCPtr);
      SWIGTYPE_p_FbxPropertyTT_EFbxRotationOrder_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxPropertyTT_EFbxRotationOrder_t(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyBool RotationSpaceForLimitOnly {
    set {
      fbx_wrapperPINVOKE.FbxNode_RotationSpaceForLimitOnly_set(swigCPtr, FbxPropertyBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_RotationSpaceForLimitOnly_get(swigCPtr);
      FbxPropertyBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble RotationStiffnessX {
    set {
      fbx_wrapperPINVOKE.FbxNode_RotationStiffnessX_set(swigCPtr, FbxPropertyDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_RotationStiffnessX_get(swigCPtr);
      FbxPropertyDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble RotationStiffnessY {
    set {
      fbx_wrapperPINVOKE.FbxNode_RotationStiffnessY_set(swigCPtr, FbxPropertyDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_RotationStiffnessY_get(swigCPtr);
      FbxPropertyDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble RotationStiffnessZ {
    set {
      fbx_wrapperPINVOKE.FbxNode_RotationStiffnessZ_set(swigCPtr, FbxPropertyDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_RotationStiffnessZ_get(swigCPtr);
      FbxPropertyDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble AxisLen {
    set {
      fbx_wrapperPINVOKE.FbxNode_AxisLen_set(swigCPtr, FbxPropertyDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_AxisLen_get(swigCPtr);
      FbxPropertyDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble3 PreRotation {
    set {
      fbx_wrapperPINVOKE.FbxNode_PreRotation_set(swigCPtr, FbxPropertyDouble3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_PreRotation_get(swigCPtr);
      FbxPropertyDouble3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble3(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble3 PostRotation {
    set {
      fbx_wrapperPINVOKE.FbxNode_PostRotation_set(swigCPtr, FbxPropertyDouble3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_PostRotation_get(swigCPtr);
      FbxPropertyDouble3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble3(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyBool RotationActive {
    set {
      fbx_wrapperPINVOKE.FbxNode_RotationActive_set(swigCPtr, FbxPropertyBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_RotationActive_get(swigCPtr);
      FbxPropertyBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble3 RotationMin {
    set {
      fbx_wrapperPINVOKE.FbxNode_RotationMin_set(swigCPtr, FbxPropertyDouble3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_RotationMin_get(swigCPtr);
      FbxPropertyDouble3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble3(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble3 RotationMax {
    set {
      fbx_wrapperPINVOKE.FbxNode_RotationMax_set(swigCPtr, FbxPropertyDouble3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_RotationMax_get(swigCPtr);
      FbxPropertyDouble3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble3(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyBool RotationMinX {
    set {
      fbx_wrapperPINVOKE.FbxNode_RotationMinX_set(swigCPtr, FbxPropertyBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_RotationMinX_get(swigCPtr);
      FbxPropertyBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyBool RotationMinY {
    set {
      fbx_wrapperPINVOKE.FbxNode_RotationMinY_set(swigCPtr, FbxPropertyBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_RotationMinY_get(swigCPtr);
      FbxPropertyBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyBool RotationMinZ {
    set {
      fbx_wrapperPINVOKE.FbxNode_RotationMinZ_set(swigCPtr, FbxPropertyBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_RotationMinZ_get(swigCPtr);
      FbxPropertyBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyBool RotationMaxX {
    set {
      fbx_wrapperPINVOKE.FbxNode_RotationMaxX_set(swigCPtr, FbxPropertyBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_RotationMaxX_get(swigCPtr);
      FbxPropertyBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyBool RotationMaxY {
    set {
      fbx_wrapperPINVOKE.FbxNode_RotationMaxY_set(swigCPtr, FbxPropertyBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_RotationMaxY_get(swigCPtr);
      FbxPropertyBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyBool RotationMaxZ {
    set {
      fbx_wrapperPINVOKE.FbxNode_RotationMaxZ_set(swigCPtr, FbxPropertyBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_RotationMaxZ_get(swigCPtr);
      FbxPropertyBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyBool(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_FbxPropertyTT_FbxTransform__EInheritType_t InheritType {
    set {
      fbx_wrapperPINVOKE.FbxNode_InheritType_set(swigCPtr, SWIGTYPE_p_FbxPropertyTT_FbxTransform__EInheritType_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_InheritType_get(swigCPtr);
      SWIGTYPE_p_FbxPropertyTT_FbxTransform__EInheritType_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxPropertyTT_FbxTransform__EInheritType_t(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyBool ScalingActive {
    set {
      fbx_wrapperPINVOKE.FbxNode_ScalingActive_set(swigCPtr, FbxPropertyBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_ScalingActive_get(swigCPtr);
      FbxPropertyBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble3 ScalingMin {
    set {
      fbx_wrapperPINVOKE.FbxNode_ScalingMin_set(swigCPtr, FbxPropertyDouble3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_ScalingMin_get(swigCPtr);
      FbxPropertyDouble3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble3(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble3 ScalingMax {
    set {
      fbx_wrapperPINVOKE.FbxNode_ScalingMax_set(swigCPtr, FbxPropertyDouble3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_ScalingMax_get(swigCPtr);
      FbxPropertyDouble3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble3(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyBool ScalingMinX {
    set {
      fbx_wrapperPINVOKE.FbxNode_ScalingMinX_set(swigCPtr, FbxPropertyBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_ScalingMinX_get(swigCPtr);
      FbxPropertyBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyBool ScalingMinY {
    set {
      fbx_wrapperPINVOKE.FbxNode_ScalingMinY_set(swigCPtr, FbxPropertyBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_ScalingMinY_get(swigCPtr);
      FbxPropertyBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyBool ScalingMinZ {
    set {
      fbx_wrapperPINVOKE.FbxNode_ScalingMinZ_set(swigCPtr, FbxPropertyBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_ScalingMinZ_get(swigCPtr);
      FbxPropertyBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyBool ScalingMaxX {
    set {
      fbx_wrapperPINVOKE.FbxNode_ScalingMaxX_set(swigCPtr, FbxPropertyBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_ScalingMaxX_get(swigCPtr);
      FbxPropertyBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyBool ScalingMaxY {
    set {
      fbx_wrapperPINVOKE.FbxNode_ScalingMaxY_set(swigCPtr, FbxPropertyBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_ScalingMaxY_get(swigCPtr);
      FbxPropertyBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyBool ScalingMaxZ {
    set {
      fbx_wrapperPINVOKE.FbxNode_ScalingMaxZ_set(swigCPtr, FbxPropertyBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_ScalingMaxZ_get(swigCPtr);
      FbxPropertyBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble3 GeometricTranslation {
    set {
      fbx_wrapperPINVOKE.FbxNode_GeometricTranslation_set(swigCPtr, FbxPropertyDouble3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GeometricTranslation_get(swigCPtr);
      FbxPropertyDouble3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble3(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble3 GeometricRotation {
    set {
      fbx_wrapperPINVOKE.FbxNode_GeometricRotation_set(swigCPtr, FbxPropertyDouble3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GeometricRotation_get(swigCPtr);
      FbxPropertyDouble3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble3(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble3 GeometricScaling {
    set {
      fbx_wrapperPINVOKE.FbxNode_GeometricScaling_set(swigCPtr, FbxPropertyDouble3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_GeometricScaling_get(swigCPtr);
      FbxPropertyDouble3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble3(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble MinDampRangeX {
    set {
      fbx_wrapperPINVOKE.FbxNode_MinDampRangeX_set(swigCPtr, FbxPropertyDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_MinDampRangeX_get(swigCPtr);
      FbxPropertyDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble MinDampRangeY {
    set {
      fbx_wrapperPINVOKE.FbxNode_MinDampRangeY_set(swigCPtr, FbxPropertyDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_MinDampRangeY_get(swigCPtr);
      FbxPropertyDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble MinDampRangeZ {
    set {
      fbx_wrapperPINVOKE.FbxNode_MinDampRangeZ_set(swigCPtr, FbxPropertyDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_MinDampRangeZ_get(swigCPtr);
      FbxPropertyDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble MaxDampRangeX {
    set {
      fbx_wrapperPINVOKE.FbxNode_MaxDampRangeX_set(swigCPtr, FbxPropertyDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_MaxDampRangeX_get(swigCPtr);
      FbxPropertyDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble MaxDampRangeY {
    set {
      fbx_wrapperPINVOKE.FbxNode_MaxDampRangeY_set(swigCPtr, FbxPropertyDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_MaxDampRangeY_get(swigCPtr);
      FbxPropertyDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble MaxDampRangeZ {
    set {
      fbx_wrapperPINVOKE.FbxNode_MaxDampRangeZ_set(swigCPtr, FbxPropertyDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_MaxDampRangeZ_get(swigCPtr);
      FbxPropertyDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble MinDampStrengthX {
    set {
      fbx_wrapperPINVOKE.FbxNode_MinDampStrengthX_set(swigCPtr, FbxPropertyDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_MinDampStrengthX_get(swigCPtr);
      FbxPropertyDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble MinDampStrengthY {
    set {
      fbx_wrapperPINVOKE.FbxNode_MinDampStrengthY_set(swigCPtr, FbxPropertyDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_MinDampStrengthY_get(swigCPtr);
      FbxPropertyDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble MinDampStrengthZ {
    set {
      fbx_wrapperPINVOKE.FbxNode_MinDampStrengthZ_set(swigCPtr, FbxPropertyDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_MinDampStrengthZ_get(swigCPtr);
      FbxPropertyDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble MaxDampStrengthX {
    set {
      fbx_wrapperPINVOKE.FbxNode_MaxDampStrengthX_set(swigCPtr, FbxPropertyDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_MaxDampStrengthX_get(swigCPtr);
      FbxPropertyDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble MaxDampStrengthY {
    set {
      fbx_wrapperPINVOKE.FbxNode_MaxDampStrengthY_set(swigCPtr, FbxPropertyDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_MaxDampStrengthY_get(swigCPtr);
      FbxPropertyDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble MaxDampStrengthZ {
    set {
      fbx_wrapperPINVOKE.FbxNode_MaxDampStrengthZ_set(swigCPtr, FbxPropertyDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_MaxDampStrengthZ_get(swigCPtr);
      FbxPropertyDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble PreferedAngleX {
    set {
      fbx_wrapperPINVOKE.FbxNode_PreferedAngleX_set(swigCPtr, FbxPropertyDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_PreferedAngleX_get(swigCPtr);
      FbxPropertyDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble PreferedAngleY {
    set {
      fbx_wrapperPINVOKE.FbxNode_PreferedAngleY_set(swigCPtr, FbxPropertyDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_PreferedAngleY_get(swigCPtr);
      FbxPropertyDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyDouble PreferedAngleZ {
    set {
      fbx_wrapperPINVOKE.FbxNode_PreferedAngleZ_set(swigCPtr, FbxPropertyDouble.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_PreferedAngleZ_get(swigCPtr);
      FbxPropertyDouble ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyDouble(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_FbxPropertyTT_FbxObject_p_t LookAtProperty {
    set {
      fbx_wrapperPINVOKE.FbxNode_LookAtProperty_set(swigCPtr, SWIGTYPE_p_FbxPropertyTT_FbxObject_p_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_LookAtProperty_get(swigCPtr);
      SWIGTYPE_p_FbxPropertyTT_FbxObject_p_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxPropertyTT_FbxObject_p_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_FbxPropertyTT_FbxObject_p_t UpVectorProperty {
    set {
      fbx_wrapperPINVOKE.FbxNode_UpVectorProperty_set(swigCPtr, SWIGTYPE_p_FbxPropertyTT_FbxObject_p_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_UpVectorProperty_get(swigCPtr);
      SWIGTYPE_p_FbxPropertyTT_FbxObject_p_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxPropertyTT_FbxObject_p_t(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyBool Show {
    set {
      fbx_wrapperPINVOKE.FbxNode_Show_set(swigCPtr, FbxPropertyBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_Show_get(swigCPtr);
      FbxPropertyBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyBool NegativePercentShapeSupport {
    set {
      fbx_wrapperPINVOKE.FbxNode_NegativePercentShapeSupport_set(swigCPtr, FbxPropertyBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_NegativePercentShapeSupport_get(swigCPtr);
      FbxPropertyBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyBool(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_FbxPropertyTT_int_t DefaultAttributeIndex {
    set {
      fbx_wrapperPINVOKE.FbxNode_DefaultAttributeIndex_set(swigCPtr, SWIGTYPE_p_FbxPropertyTT_int_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_DefaultAttributeIndex_get(swigCPtr);
      SWIGTYPE_p_FbxPropertyTT_int_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxPropertyTT_int_t(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyBool Freeze {
    set {
      fbx_wrapperPINVOKE.FbxNode_Freeze_set(swigCPtr, FbxPropertyBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_Freeze_get(swigCPtr);
      FbxPropertyBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyBool(cPtr, false);
      return ret;
    } 
  }

  public FbxPropertyBool LODBox {
    set {
      fbx_wrapperPINVOKE.FbxNode_LODBox_set(swigCPtr, FbxPropertyBool.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_LODBox_get(swigCPtr);
      FbxPropertyBool ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxPropertyBool(cPtr, false);
      return ret;
    } 
  }

  public class Pivot : global::System.IDisposable {
    private global::System.Runtime.InteropServices.HandleRef swigCPtr;
    protected bool swigCMemOwn;
  
    internal Pivot(global::System.IntPtr cPtr, bool cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
    }
  
    internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Pivot obj) {
      return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
    }
  
    ~Pivot() {
      Dispose();
    }
  
    public virtual void Dispose() {
      lock(this) {
        if (swigCPtr.Handle != global::System.IntPtr.Zero) {
          if (swigCMemOwn) {
            swigCMemOwn = false;
            fbx_wrapperPINVOKE.delete_FbxNode_Pivot(swigCPtr);
          }
          swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
        }
        global::System.GC.SuppressFinalize(this);
      }
    }
  
    public static FbxVector4 sZeroVector {
      get {
        global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_Pivot_sZeroVector_get();
        FbxVector4 ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxVector4(cPtr, false);
        return ret;
      } 
    }
  
    public static FbxVector4 sOneVector {
      get {
        global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_Pivot_sOneVector_get();
        FbxVector4 ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxVector4(cPtr, false);
        return ret;
      } 
    }
  
    public Pivot() : this(fbx_wrapperPINVOKE.new_FbxNode_Pivot(), true) {
    }
  
    public void Reset() {
      fbx_wrapperPINVOKE.FbxNode_Pivot_Reset(swigCPtr);
    }
  
    public FbxVector4 GetRotationOffset() {
      FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_Pivot_GetRotationOffset(swigCPtr), false);
      return ret;
    }
  
    public void SetRotationOffset(FbxVector4 pV) {
      fbx_wrapperPINVOKE.FbxNode_Pivot_SetRotationOffset(swigCPtr, FbxVector4.getCPtr(pV));
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    }
  
    public FbxVector4 GetRotationPivot() {
      FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_Pivot_GetRotationPivot(swigCPtr), false);
      return ret;
    }
  
    public void SetRotationPivot(FbxVector4 pV) {
      fbx_wrapperPINVOKE.FbxNode_Pivot_SetRotationPivot(swigCPtr, FbxVector4.getCPtr(pV));
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    }
  
    public FbxVector4 GetPreRotation() {
      FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_Pivot_GetPreRotation(swigCPtr), false);
      return ret;
    }
  
    public void SetPreRotation(FbxVector4 pV) {
      fbx_wrapperPINVOKE.FbxNode_Pivot_SetPreRotation(swigCPtr, FbxVector4.getCPtr(pV));
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    }
  
    public FbxVector4 GetPostRotation() {
      FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_Pivot_GetPostRotation(swigCPtr), false);
      return ret;
    }
  
    public void SetPostRotation(FbxVector4 pV) {
      fbx_wrapperPINVOKE.FbxNode_Pivot_SetPostRotation(swigCPtr, FbxVector4.getCPtr(pV));
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    }
  
    public FbxVector4 GetScalingOffset() {
      FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_Pivot_GetScalingOffset(swigCPtr), false);
      return ret;
    }
  
    public void SetScalingOffset(FbxVector4 pV) {
      fbx_wrapperPINVOKE.FbxNode_Pivot_SetScalingOffset(swigCPtr, FbxVector4.getCPtr(pV));
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    }
  
    public FbxVector4 GetScalingPivot() {
      FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_Pivot_GetScalingPivot(swigCPtr), false);
      return ret;
    }
  
    public void SetScalingPivot(FbxVector4 pV) {
      fbx_wrapperPINVOKE.FbxNode_Pivot_SetScalingPivot(swigCPtr, FbxVector4.getCPtr(pV));
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    }
  
    public FbxVector4 GetGeometricTranslation() {
      FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_Pivot_GetGeometricTranslation(swigCPtr), false);
      return ret;
    }
  
    public void SetGeometricTranslation(FbxVector4 pV) {
      fbx_wrapperPINVOKE.FbxNode_Pivot_SetGeometricTranslation(swigCPtr, FbxVector4.getCPtr(pV));
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    }
  
    public FbxVector4 GetGeometricRotation() {
      FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_Pivot_GetGeometricRotation(swigCPtr), false);
      return ret;
    }
  
    public void SetGeometricRotation(FbxVector4 pV) {
      fbx_wrapperPINVOKE.FbxNode_Pivot_SetGeometricRotation(swigCPtr, FbxVector4.getCPtr(pV));
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    }
  
    public FbxVector4 GetGeometricScaling() {
      FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_Pivot_GetGeometricScaling(swigCPtr), false);
      return ret;
    }
  
    public void SetGeometricScaling(FbxVector4 pV) {
      fbx_wrapperPINVOKE.FbxNode_Pivot_SetGeometricScaling(swigCPtr, FbxVector4.getCPtr(pV));
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    }
  
    public SWIGTYPE_p_EFbxRotationOrder GetRotationOrder() {
      SWIGTYPE_p_EFbxRotationOrder ret = new SWIGTYPE_p_EFbxRotationOrder(fbx_wrapperPINVOKE.FbxNode_Pivot_GetRotationOrder(swigCPtr), true);
      return ret;
    }
  
    public void SetRotationOrder(SWIGTYPE_p_EFbxRotationOrder pROrder) {
      fbx_wrapperPINVOKE.FbxNode_Pivot_SetRotationOrder(swigCPtr, SWIGTYPE_p_EFbxRotationOrder.getCPtr(pROrder));
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    }
  
    public bool GetRotationSpaceForLimitOnly() {
      bool ret = fbx_wrapperPINVOKE.FbxNode_Pivot_GetRotationSpaceForLimitOnly(swigCPtr);
      return ret;
    }
  
    public void SetRotationSpaceForLimitOnly(bool pVal) {
      fbx_wrapperPINVOKE.FbxNode_Pivot_SetRotationSpaceForLimitOnly(swigCPtr, pVal);
    }
  
    public SWIGTYPE_p_EFbxQuatInterpMode GetQuaternionInterpolate() {
      SWIGTYPE_p_EFbxQuatInterpMode ret = new SWIGTYPE_p_EFbxQuatInterpMode(fbx_wrapperPINVOKE.FbxNode_Pivot_GetQuaternionInterpolate(swigCPtr), true);
      return ret;
    }
  
    public void SetQuaternionInterpolate(SWIGTYPE_p_EFbxQuatInterpMode pVal) {
      fbx_wrapperPINVOKE.FbxNode_Pivot_SetQuaternionInterpolate(swigCPtr, SWIGTYPE_p_EFbxQuatInterpMode.getCPtr(pVal));
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    }
  
    public FbxNode.EPivotState GetPivotState() {
      FbxNode.EPivotState ret = (FbxNode.EPivotState)fbx_wrapperPINVOKE.FbxNode_Pivot_GetPivotState(swigCPtr);
      return ret;
    }
  
    public void SetPivotState(FbxNode.EPivotState pVal) {
      fbx_wrapperPINVOKE.FbxNode_Pivot_SetPivotState(swigCPtr, (int)pVal);
    }
  
  }

  public class Pivots : global::System.IDisposable {
    private global::System.Runtime.InteropServices.HandleRef swigCPtr;
    protected bool swigCMemOwn;
  
    internal Pivots(global::System.IntPtr cPtr, bool cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
    }
  
    internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Pivots obj) {
      return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
    }
  
    ~Pivots() {
      Dispose();
    }
  
    public virtual void Dispose() {
      lock(this) {
        if (swigCPtr.Handle != global::System.IntPtr.Zero) {
          if (swigCMemOwn) {
            swigCMemOwn = false;
            fbx_wrapperPINVOKE.delete_FbxNode_Pivots(swigCPtr);
          }
          swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
        }
        global::System.GC.SuppressFinalize(this);
      }
    }
  
    public Pivots() : this(fbx_wrapperPINVOKE.new_FbxNode_Pivots(), true) {
    }
  
    public FbxNode.Pivot Get(int id) {
      FbxNode.Pivot ret = new FbxNode.Pivot(fbx_wrapperPINVOKE.FbxNode_Pivots_Get(swigCPtr, id), false);
      return ret;
    }
  
    public FbxVector4 GetRotationOffset(int id) {
      FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_Pivots_GetRotationOffset(swigCPtr, id), false);
      return ret;
    }
  
    public void SetRotationOffset(int id, FbxVector4 pV) {
      fbx_wrapperPINVOKE.FbxNode_Pivots_SetRotationOffset(swigCPtr, id, FbxVector4.getCPtr(pV));
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    }
  
    public FbxVector4 GetRotationPivot(int id) {
      FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_Pivots_GetRotationPivot(swigCPtr, id), false);
      return ret;
    }
  
    public void SetRotationPivot(int id, FbxVector4 pV) {
      fbx_wrapperPINVOKE.FbxNode_Pivots_SetRotationPivot(swigCPtr, id, FbxVector4.getCPtr(pV));
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    }
  
    public FbxVector4 GetPreRotation(int id) {
      FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_Pivots_GetPreRotation(swigCPtr, id), false);
      return ret;
    }
  
    public void SetPreRotation(int id, FbxVector4 pV) {
      fbx_wrapperPINVOKE.FbxNode_Pivots_SetPreRotation(swigCPtr, id, FbxVector4.getCPtr(pV));
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    }
  
    public FbxVector4 GetPostRotation(int id) {
      FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_Pivots_GetPostRotation(swigCPtr, id), false);
      return ret;
    }
  
    public void SetPostRotation(int id, FbxVector4 pV) {
      fbx_wrapperPINVOKE.FbxNode_Pivots_SetPostRotation(swigCPtr, id, FbxVector4.getCPtr(pV));
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    }
  
    public FbxVector4 GetScalingOffset(int id) {
      FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_Pivots_GetScalingOffset(swigCPtr, id), false);
      return ret;
    }
  
    public void SetScalingOffset(int id, FbxVector4 pV) {
      fbx_wrapperPINVOKE.FbxNode_Pivots_SetScalingOffset(swigCPtr, id, FbxVector4.getCPtr(pV));
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    }
  
    public FbxVector4 GetScalingPivot(int id) {
      FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_Pivots_GetScalingPivot(swigCPtr, id), false);
      return ret;
    }
  
    public void SetScalingPivot(int id, FbxVector4 pV) {
      fbx_wrapperPINVOKE.FbxNode_Pivots_SetScalingPivot(swigCPtr, id, FbxVector4.getCPtr(pV));
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    }
  
    public FbxVector4 GetGeometricTranslation(int id) {
      FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_Pivots_GetGeometricTranslation(swigCPtr, id), false);
      return ret;
    }
  
    public void SetGeometricTranslation(int id, FbxVector4 pV) {
      fbx_wrapperPINVOKE.FbxNode_Pivots_SetGeometricTranslation(swigCPtr, id, FbxVector4.getCPtr(pV));
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    }
  
    public FbxVector4 GetGeometricRotation(int id) {
      FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_Pivots_GetGeometricRotation(swigCPtr, id), false);
      return ret;
    }
  
    public void SetGeometricRotation(int id, FbxVector4 pV) {
      fbx_wrapperPINVOKE.FbxNode_Pivots_SetGeometricRotation(swigCPtr, id, FbxVector4.getCPtr(pV));
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    }
  
    public FbxVector4 GetGeometricScaling(int id) {
      FbxVector4 ret = new FbxVector4(fbx_wrapperPINVOKE.FbxNode_Pivots_GetGeometricScaling(swigCPtr, id), false);
      return ret;
    }
  
    public void SetGeometricScaling(int id, FbxVector4 pV) {
      fbx_wrapperPINVOKE.FbxNode_Pivots_SetGeometricScaling(swigCPtr, id, FbxVector4.getCPtr(pV));
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    }
  
    public bool GetRotationSpaceForLimitOnly(int id) {
      bool ret = fbx_wrapperPINVOKE.FbxNode_Pivots_GetRotationSpaceForLimitOnly(swigCPtr, id);
      return ret;
    }
  
    public void SetRotationSpaceForLimitOnly(int id, bool pV) {
      fbx_wrapperPINVOKE.FbxNode_Pivots_SetRotationSpaceForLimitOnly(swigCPtr, id, pV);
    }
  
    public SWIGTYPE_p_EFbxQuatInterpMode GetQuaternionInterpolate(int id) {
      SWIGTYPE_p_EFbxQuatInterpMode ret = new SWIGTYPE_p_EFbxQuatInterpMode(fbx_wrapperPINVOKE.FbxNode_Pivots_GetQuaternionInterpolate(swigCPtr, id), true);
      return ret;
    }
  
    public void SetQuaternionInterpolate(int id, SWIGTYPE_p_EFbxQuatInterpMode pV) {
      fbx_wrapperPINVOKE.FbxNode_Pivots_SetQuaternionInterpolate(swigCPtr, id, SWIGTYPE_p_EFbxQuatInterpMode.getCPtr(pV));
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    }
  
    public SWIGTYPE_p_EFbxRotationOrder GetRotationOrder(int id) {
      SWIGTYPE_p_EFbxRotationOrder ret = new SWIGTYPE_p_EFbxRotationOrder(fbx_wrapperPINVOKE.FbxNode_Pivots_GetRotationOrder(swigCPtr, id), true);
      return ret;
    }
  
    public void SetRotationOrder(int id, SWIGTYPE_p_EFbxRotationOrder pROrder) {
      fbx_wrapperPINVOKE.FbxNode_Pivots_SetRotationOrder(swigCPtr, id, SWIGTYPE_p_EFbxRotationOrder.getCPtr(pROrder));
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    }
  
    public FbxNode.EPivotState GetPivotState(int id) {
      FbxNode.EPivotState ret = (FbxNode.EPivotState)fbx_wrapperPINVOKE.FbxNode_Pivots_GetPivotState(swigCPtr, id);
      return ret;
    }
  
    public void SetPivotState(int id, FbxNode.EPivotState pVal) {
      fbx_wrapperPINVOKE.FbxNode_Pivots_SetPivotState(swigCPtr, id, (int)pVal);
    }
  
    public void Reset() {
      fbx_wrapperPINVOKE.FbxNode_Pivots_Reset(swigCPtr);
    }
  
  }

  public class LinkToCharacter : global::System.IDisposable {
    private global::System.Runtime.InteropServices.HandleRef swigCPtr;
    protected bool swigCMemOwn;
  
    internal LinkToCharacter(global::System.IntPtr cPtr, bool cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
    }
  
    internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LinkToCharacter obj) {
      return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
    }
  
    ~LinkToCharacter() {
      Dispose();
    }
  
    public virtual void Dispose() {
      lock(this) {
        if (swigCPtr.Handle != global::System.IntPtr.Zero) {
          if (swigCMemOwn) {
            swigCMemOwn = false;
            fbx_wrapperPINVOKE.delete_FbxNode_LinkToCharacter(swigCPtr);
          }
          swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
        }
        global::System.GC.SuppressFinalize(this);
      }
    }
  
    public bool eq(FbxNode.LinkToCharacter pLinkToCharacter) {
      bool ret = fbx_wrapperPINVOKE.FbxNode_LinkToCharacter_eq(swigCPtr, FbxNode.LinkToCharacter.getCPtr(pLinkToCharacter));
      if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    }
  
    public SWIGTYPE_p_FbxCharacter mCharacter {
      set {
        fbx_wrapperPINVOKE.FbxNode_LinkToCharacter_mCharacter_set(swigCPtr, SWIGTYPE_p_FbxCharacter.getCPtr(value));
      } 
      get {
        global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_LinkToCharacter_mCharacter_get(swigCPtr);
        SWIGTYPE_p_FbxCharacter ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_FbxCharacter(cPtr, false);
        return ret;
      } 
    }
  
    public int mType {
      set {
        fbx_wrapperPINVOKE.FbxNode_LinkToCharacter_mType_set(swigCPtr, value);
      } 
      get {
        int ret = fbx_wrapperPINVOKE.FbxNode_LinkToCharacter_mType_get(swigCPtr);
        return ret;
      } 
    }
  
    public int mIndex {
      set {
        fbx_wrapperPINVOKE.FbxNode_LinkToCharacter_mIndex_set(swigCPtr, value);
      } 
      get {
        int ret = fbx_wrapperPINVOKE.FbxNode_LinkToCharacter_mIndex_get(swigCPtr);
        return ret;
      } 
    }
  
    public int mSubIndex {
      set {
        fbx_wrapperPINVOKE.FbxNode_LinkToCharacter_mSubIndex_set(swigCPtr, value);
      } 
      get {
        int ret = fbx_wrapperPINVOKE.FbxNode_LinkToCharacter_mSubIndex_get(swigCPtr);
        return ret;
      } 
    }
  
    public LinkToCharacter() : this(fbx_wrapperPINVOKE.new_FbxNode_LinkToCharacter(), true) {
    }
  
  }

  public void AddChildName(string pChildName) {
    fbx_wrapperPINVOKE.FbxNode_AddChildName(swigCPtr, pChildName);
  }

  public string GetChildName(uint pIndex) {
    string ret = fbx_wrapperPINVOKE.FbxNode_GetChildName(swigCPtr, pIndex);
    return ret;
  }

  public uint GetChildNameCount() {
    uint ret = fbx_wrapperPINVOKE.FbxNode_GetChildNameCount(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_FbxTransform GetTransform() {
    SWIGTYPE_p_FbxTransform ret = new SWIGTYPE_p_FbxTransform(fbx_wrapperPINVOKE.FbxNode_GetTransform(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_FbxLimits GetTranslationLimits() {
    SWIGTYPE_p_FbxLimits ret = new SWIGTYPE_p_FbxLimits(fbx_wrapperPINVOKE.FbxNode_GetTranslationLimits(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_FbxLimits GetRotationLimits() {
    SWIGTYPE_p_FbxLimits ret = new SWIGTYPE_p_FbxLimits(fbx_wrapperPINVOKE.FbxNode_GetRotationLimits(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_FbxLimits GetScalingLimits() {
    SWIGTYPE_p_FbxLimits ret = new SWIGTYPE_p_FbxLimits(fbx_wrapperPINVOKE.FbxNode_GetScalingLimits(swigCPtr), false);
    return ret;
  }

  public FbxNode.Pivots GetPivots() {
    FbxNode.Pivots ret = new FbxNode.Pivots(fbx_wrapperPINVOKE.FbxNode_GetPivots(swigCPtr), false);
    return ret;
  }

  public void UpdatePivotsAndLimitsFromProperties() {
    fbx_wrapperPINVOKE.FbxNode_UpdatePivotsAndLimitsFromProperties(swigCPtr);
  }

  public void UpdatePropertiesFromPivotsAndLimits() {
    fbx_wrapperPINVOKE.FbxNode_UpdatePropertiesFromPivotsAndLimits(swigCPtr);
  }

  public void SetRotationActiveProperty(bool pVal) {
    fbx_wrapperPINVOKE.FbxNode_SetRotationActiveProperty(swigCPtr, pVal);
  }

  public void PivotSetToMBTransform(FbxNode.EPivotSet pPivotSet) {
    fbx_wrapperPINVOKE.FbxNode_PivotSetToMBTransform(swigCPtr, (int)pPivotSet);
  }

  public int AddCharacterLink(SWIGTYPE_p_FbxCharacter pCharacter, int pCharacterLinkType, int pNodeId, int pNodeSubId) {
    int ret = fbx_wrapperPINVOKE.FbxNode_AddCharacterLink(swigCPtr, SWIGTYPE_p_FbxCharacter.getCPtr(pCharacter), pCharacterLinkType, pNodeId, pNodeSubId);
    return ret;
  }

  public int RemoveCharacterLink(SWIGTYPE_p_FbxCharacter pCharacter, int pCharacterLinkType, int pNodeId, int pNodeSubId) {
    int ret = fbx_wrapperPINVOKE.FbxNode_RemoveCharacterLink(swigCPtr, SWIGTYPE_p_FbxCharacter.getCPtr(pCharacter), pCharacterLinkType, pNodeId, pNodeSubId);
    return ret;
  }

  public FbxNode DeepCloneWithNodeAttributes() {
    global::System.IntPtr cPtr = fbx_wrapperPINVOKE.FbxNode_DeepCloneWithNodeAttributes(swigCPtr);
    FbxNode ret = (cPtr == global::System.IntPtr.Zero) ? null : new FbxNode(cPtr, false);
    return ret;
  }

  public override FbxObject Copy(FbxObject pObject) {
    FbxObject ret = new FbxObject(fbx_wrapperPINVOKE.FbxNode_Copy(swigCPtr, FbxObject.getCPtr(pObject)), false);
    if (fbx_wrapperPINVOKE.SWIGPendingException.Pending) throw fbx_wrapperPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override string GetTypeName() {
    string ret = fbx_wrapperPINVOKE.FbxNode_GetTypeName(swigCPtr);
    return ret;
  }

  public override SWIGTYPE_p_FbxStringList GetTypeFlags() {
    SWIGTYPE_p_FbxStringList ret = new SWIGTYPE_p_FbxStringList(fbx_wrapperPINVOKE.FbxNode_GetTypeFlags(swigCPtr), true);
    return ret;
  }

  public FbxNode.ECullingType mCullingType {
    set {
      fbx_wrapperPINVOKE.FbxNode_mCullingType_set(swigCPtr, (int)value);
    } 
    get {
      FbxNode.ECullingType ret = (FbxNode.ECullingType)fbx_wrapperPINVOKE.FbxNode_mCullingType_get(swigCPtr);
      return ret;
    } 
  }

  public bool mCorrectInheritType {
    set {
      fbx_wrapperPINVOKE.FbxNode_mCorrectInheritType_set(swigCPtr, value);
    } 
    get {
      bool ret = fbx_wrapperPINVOKE.FbxNode_mCorrectInheritType_get(swigCPtr);
      return ret;
    } 
  }

  public enum EShadingMode {
    eHardShading,
    eWireFrame,
    eFlatShading,
    eLightShading,
    eTextureShading,
    eFullShading
  }

  public enum EPivotSet {
    eSourcePivot,
    eDestinationPivot
  }

  public enum EPivotState {
    ePivotActive,
    ePivotReference
  }

  public enum ECullingType {
    eCullingOff,
    eCullingOnCCW,
    eCullingOnCW
  }

}

}
