//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Fbx {

public class FbxObjectPropertyChangedBase : FbxEventBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal FbxObjectPropertyChangedBase(global::System.IntPtr cPtr, bool cMemoryOwn) : base(fbx_wrapperPINVOKE.FbxObjectPropertyChangedBase_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FbxObjectPropertyChangedBase obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FbxObjectPropertyChangedBase() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          fbx_wrapperPINVOKE.delete_FbxObjectPropertyChangedBase(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static void ForceTypeId(int pTypeId) {
    fbx_wrapperPINVOKE.FbxObjectPropertyChangedBase_ForceTypeId(pTypeId);
  }

  public override int GetTypeId() {
    int ret = fbx_wrapperPINVOKE.FbxObjectPropertyChangedBase_GetTypeId(swigCPtr);
    return ret;
  }

  public static int GetStaticTypeId() {
    int ret = fbx_wrapperPINVOKE.FbxObjectPropertyChangedBase_GetStaticTypeId();
    return ret;
  }

}

}
